version: 2.1
jobs:
    build:
        docker:
            - image: circleci/golang:1.16

        steps:
        - checkout
        - run:
            name: Install sudo
            command: apt-get install -y sudo
        - run:
            name: Run tests
            command: sudo go test -v ./...
