version: 2.1
jobs:
    build:
        docker:
            - image: circleci/golang:1.16

        steps:
        - checkout
        - run:
            name: Install libcryptsetup dependencies
            command: sudo apt-get install -y libcryptsetup-12 libcryptsetup-dev
        - run:
            name: Run tests
            command: sudo go test -v ./...
